name: Cog Unit Tests
on:
  pull_request:
  push:

jobs:
  run-tests:
    name: Run cog unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio
      - name: Install Red-DiscordBot
        run: |
          python setup.py install
      - name: Run unit tests
        run: |
          pytest cogs/*/test* 
